### WARNING ###
#
# This file is deprecated!
# To deploy CERNBox, please refer to CERNBOX.yaml
#
###


### POD ###
apiVersion: v1
kind: Pod
metadata:
  name: &name cernboxgateway
  namespace: boxed
  labels:
    app: *name
spec:
  restartPolicy: Always
  nodeSelector:
    nodeApp: *name
  hostname: *name
  subdomain: *name
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: cernboxgateway
    image: gitlab-registry.cern.ch/cernbox/boxedhub/cernboxgateway:v0.3
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      protocol: TCP
      hostPort: 80
      containerPort: 80
    - name: https
      protocol: TCP
      hostPort: 443
      containerPort: 443
    volumeMounts:
    - name: &vm_certs certs
      mountPath: /etc/boxed/certs
    - name: &vm_logs cboxgw-logs
      mountPath: /var/log/nginx
    env:
    ### PodInfo ###
    - name: PODINFO_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: PODINFO_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: PODINFO_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: PODINFO_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: PODINFO_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    ###
    - name: THIS_CONTAINER
      value: "CERNBOXGATEWAY"
    - name: DEPLOYMENT_TYPE
      value: "kubernetes"
    - name: HOSTNAME            # Assume the gateway is exposed directly on the host where it runs
      valueFrom:                # No Kubernetes services defined
        fieldRef:               # Entrypoint will be: https://<nodeName>
          fieldPath: spec.nodeName
    - name: HTTP_PORT
      value: "80"
    - name: HTTPS_PORT
      value: "443"
    - name: EOS_MGM_ALIAS
      value: "eos-mgm.eos-mgm.boxed.svc.cluster.local"
    - name: EOS_MGM_ALIAS_PORT
      value: "8000"
    - name: SWAN_BACKEND
      #value: "up2kube-master.cern.ch"
      value: "up2kube-swan.cern.ch"
    - name: SWAN_BACKEND_PORT
      #value: "30443"
      value: "443"
    - name: OWNCLOUD_BACKEND
      value: "cernbox.cernbox.boxed.svc.cluster.local"
    - name: OWNCLOUD_BACKEND_PORT
      value: "443"
    - name: LDAP_BACKEND1
      value: "ldap.boxed.svc.cluster.local"
    - name: LDAP_BACKEND2
      value: "ldap.boxed.svc.cluster.local"
    - name: WEBDAV_CLIENT_CERT_PORT
      value: "4443"
  volumes:
  - name: *vm_certs
    secret:
      secretName: certs
      defaultMode: 0644
  - name: *vm_logs
    hostPath:
      path: /var/kubeVolumes/cboxgw_logs
      type: DirectoryOrCreate
---
### SERVICE ###
apiVersion: v1
kind: Service
metadata:
  name: &name cernboxgateway
  namespace: boxed
spec:
  selector:
    app: *name
  clusterIP: None
  ports:
  - name: http          # Required only when multiple ports (>1) are defined
    protocol: TCP
    port: 80            # Port outside
    targetPort: 80      # Port being served on the container
    #nodePort: 30081     # Port on the master node from which you reach the service
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    #nodePort: 30444    
  type: ClusterIP
  #type: NodePort
